version: '3.0'

services:
  database:
    image: mysql:8.0.35
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    volumes:
      - database:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  webapp:
    build: ./webapp
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${HTTP_PORT}:80
    restart: always
    volumes:
      - ./webapp:/usr/src/myapp

volumes:
  database:
